/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carshipment_project;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class AccountsAdmin extends javax.swing.JFrame {

    /**
     * Creates new form AccountsAdmin
     */
    public AccountsAdmin() {
        initComponents();
    }
      public void close()
    {
        WindowEvent winCloseEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winCloseEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        totalsold = new javax.swing.JLabel();
        turnover = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        totaldue = new javax.swing.JLabel();
        invesment = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Total Sold");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(22, 143, 98, 32);

        jLabel2.setText("Total Invesment");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(22, 90, 98, 35);

        jLabel3.setText("Turn Over");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(22, 243, 98, 32);

        totalsold.setText("----------");
        getContentPane().add(totalsold);
        totalsold.setBounds(151, 147, 112, 25);

        turnover.setText("----------");
        getContentPane().add(turnover);
        turnover.setBounds(151, 247, 112, 24);

        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(383, 181, 110, 25);

        jLabel7.setText("Due");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(22, 193, 31, 16);

        totaldue.setText("---------");
        getContentPane().add(totaldue);
        totaldue.setBounds(151, 193, 112, 16);
        getContentPane().add(invesment);
        invesment.setBounds(151, 96, 140, 22);

        jButton2.setText("Show Stats");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(383, 95, 120, 25);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carshipment_project/Flag_of_Taliban_(original).svg.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 870, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Admin_Home hm =new Admin_Home();
        hm.setVisible(true);
        hm.setSize(790,430);
        close();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
             Class.forName("oracle.jdbc.driver.OracleDriver");
             Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","tiger");
             PreparedStatement ps = conn.prepareStatement("SELECT *  FROM SELL_INFO");
             
             ResultSet rs = ps.executeQuery();
             int tsold = 0;
             int tdue = 0;
             while(rs.next())
             {
                 tsold = Integer.parseInt(rs.getString("PAID")) + tsold;
                 totalsold.setText(String.valueOf(tsold));
                 tdue = Integer.parseInt(rs.getString("DUE")) + tdue;
                 totaldue.setText(String.valueOf(tdue));
                
                 
                 
             }
             int tover = Integer.parseInt(invesment.getText()) - (tdue + tsold);
             turnover.setText(String.valueOf(tover));
             
             
        }
        catch(Exception e){
        
            JOptionPane.showMessageDialog(null, "Worng","Click ok to try angain",JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountsAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountsAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField invesment;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel totaldue;
    private javax.swing.JLabel totalsold;
    private javax.swing.JLabel turnover;
    // End of variables declaration//GEN-END:variables
}
