/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carshipment_project;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


public class CarRecord extends javax.swing.JFrame {

    /**
     * Creates new form CarRecord
     */
    public CarRecord() {
        initComponents();
        UpdateTableSell_Info();
        UpdateTable();
        filecombo();
    }
     public void close()
    {
        WindowEvent winCloseEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winCloseEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        carrec = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        cars = new javax.swing.JTable();
        carscombo = new javax.swing.JComboBox<>();
        select = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        setprice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        setstatus = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        carrec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Brand", "Model", "Paid", "Due"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(carrec);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 23, 750, 127);

        cars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Brand", "Model", "Price", "Status", "Car Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(cars);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 180, 750, 117);

        carscombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        getContentPane().add(carscombo);
        carscombo.setBounds(165, 323, 82, 22);

        select.setText("Select");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        getContentPane().add(select);
        select.setBounds(344, 322, 130, 25);

        jLabel1.setText("Showroom Cars");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 322, 92, 16);
        getContentPane().add(setprice);
        setprice.setBounds(390, 360, 117, 22);

        jLabel2.setText("Set Price");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 360, 90, 16);

        jLabel3.setText("Set Status");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(289, 360, 70, 16);
        getContentPane().add(setstatus);
        setstatus.setBounds(150, 360, 121, 22);

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(550, 360, 150, 25);

        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 390, 120, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Sold Cars");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 60, 16);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Showroom Cars");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 157, 101, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carshipment_project/Flag_of_Taliban_(original).svg.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 760, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        Update();
    }//GEN-LAST:event_updateActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        select();
    }//GEN-LAST:event_selectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Admin_Home ahome =new Admin_Home();
        ahome.setVisible(true);
        ahome.setSize(790, 430);
        close();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarRecord().setVisible(true);
            }
        });
    }
    void UpdateTableSell_Info()
    {
        try{
             Class.forName("oracle.jdbc.driver.OracleDriver");
             Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","tiger");
             PreparedStatement ps = conn.prepareStatement("SELECT * FROM SELL_INFO ");
             
             ResultSet rs = ps.executeQuery();
             carrec.setModel(DbUtils.resultSetToTableModel(rs));
             
        }
        catch(Exception e){
        
            JOptionPane.showMessageDialog(null, "table creation failed","Click ok to try angain",JOptionPane.ERROR_MESSAGE);
        }
    }
    void UpdateTable()
    {
        try{
             Class.forName("oracle.jdbc.driver.OracleDriver");
             Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","tiger");
             PreparedStatement ps = conn.prepareStatement("SELECT BRAND,CAR_MODEL,PRICE,STATUS,CAR_NUMBER FROM CAR ");
             
             ResultSet rs = ps.executeQuery();
             cars.setModel(DbUtils.resultSetToTableModel(rs));
             
        }
        catch(Exception e){
        
            JOptionPane.showMessageDialog(null, "table creation failed","Click ok to try angain",JOptionPane.ERROR_MESSAGE);
        }
    }
    void Update()
    {
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","tiger");
            PreparedStatement ps = conn.prepareStatement("UPDATE CAR SET PRICE=?,STATUS=? WHERE CAR_MODEL=? ");
            
            ps.setString(1, setstatus.getText());
            ps.setString(2, setprice.getText());
            ps.setString(3, (String) carscombo.getSelectedItem());
            ps.executeQuery();
            setprice.setText("");
            setstatus.setText("");
            CarRecord uac =new CarRecord();
            uac.setVisible(true);
            uac.setSize(790, 460);
            close();
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    void select(){
        try{
             Class.forName("oracle.jdbc.driver.OracleDriver");
             Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","tiger");
             PreparedStatement ps = conn.prepareStatement("SELECT *  FROM CAR WHERE CAR_MODEL=? ");
             ps.setString(1, (String) carscombo.getSelectedItem());
             ResultSet rs = ps.executeQuery();
             while(rs.next())
             {
                 String price = rs.getString("PRICE");
                 setprice.setText(price);
                 String status = rs.getString("STATUS");
                 setstatus.setText(status);
                 
                 
                 
             }
             
             
             
        }
        catch(Exception e){
        
            JOptionPane.showMessageDialog(null, "Worng ","Click ok to try angain",JOptionPane.ERROR_MESSAGE);
        } 
    }
    void filecombo()
    {
        try{
             Class.forName("oracle.jdbc.driver.OracleDriver");
             Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","tiger");
             PreparedStatement ps = conn.prepareStatement("SELECT * FROM CAR ");
             
             ResultSet rs = ps.executeQuery();
             while(rs.next())
             {
                 String carmod = rs.getString("CAR_MODEL");
                 carscombo.addItem(carmod);
                 
             }
             
        }
        catch(Exception e){
        
            JOptionPane.showMessageDialog(null, "combo failde","Click ok to try angain",JOptionPane.ERROR_MESSAGE);
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable carrec;
    private javax.swing.JTable cars;
    private javax.swing.JComboBox<String> carscombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton select;
    private javax.swing.JTextField setprice;
    private javax.swing.JTextField setstatus;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
