/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carshipment_project;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author RAGIB
 */
public class Imports extends javax.swing.JFrame {

    /**
     * Creates new form Imports
     */
    public Imports() {
        initComponents();
        UpdateTable();
        filecombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        porder = new javax.swing.JTable();
        icombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        brand = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        model = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        colour = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        numofcars = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        carnumber = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        porder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Brand", "Model"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(porder);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 10, 798, 132);

        icombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        getContentPane().add(icombo);
        icombo.setBounds(150, 170, 77, 22);

        jLabel1.setText("Models");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 170, 40, 16);

        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 170, 67, 25);

        jButton2.setText("Import");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 330, 71, 25);

        jLabel2.setText("Brand");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 230, 33, 16);

        brand.setText("--------");
        getContentPane().add(brand);
        brand.setBounds(140, 230, 40, 16);

        jLabel4.setText("Model");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 230, 34, 16);

        model.setText("---------");
        getContentPane().add(model);
        model.setBounds(460, 230, 56, 16);

        jLabel6.setText("Arrival Date");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 260, 67, 16);
        getContentPane().add(date);
        date.setBounds(120, 260, 110, 22);

        jLabel7.setText("Colour");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 290, 37, 16);
        getContentPane().add(colour);
        colour.setBounds(120, 290, 110, 22);

        jLabel8.setText("Number of Cars");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 260, 90, 16);
        getContentPane().add(numofcars);
        numofcars.setBounds(470, 260, 80, 22);

        jLabel9.setText("Price");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 290, 43, 16);
        getContentPane().add(price);
        price.setBounds(470, 290, 80, 22);

        jLabel10.setText("Car Number");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(600, 290, 69, 16);
        getContentPane().add(status);
        status.setBounds(680, 260, 87, 22);

        jLabel11.setText("Status");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(600, 260, 36, 16);
        getContentPane().add(carnumber);
        carnumber.setBounds(680, 290, 87, 22);

        jButton3.setText("Return");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(350, 370, 71, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carshipment_project/Flag_of_Taliban_(original).svg.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","tiger");
            PreparedStatement ps = conn.prepareStatement("INSERT INTO CAR VALUES(?,?,?,?,?,?,?,?)");
            ps.setString(1,brand.getText());
            ps.setString(2,model.getText());
            ps.setString(3,date.getText());
            ps.setString(4,status.getText());
            ps.setString(5,colour.getText());
            ps.setString(6,numofcars.getText());
            ps.setString(7,carnumber.getText());
            ps.setString(8,price.getText());
            ps.executeQuery();
            brand.setText("");
            model.setText("");
            date.setText("");
            status.setText("");
            colour.setText("");
            numofcars.setText("");
            carnumber.setText("");
            price.setText("");
            
            PreparedStatement dsellinfo = conn.prepareStatement("DELETE FROM PLACE_ORDER WHERE MODEL =? ");
            dsellinfo.setString(1, (String) icombo.getSelectedItem());
            dsellinfo.executeQuery();
            Imports i = new Imports();
            i.setVisible(true);
            i.setSize(730, 440);
            close();
            
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        select();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Admin_Home ah= new Admin_Home();
        ah.setVisible(true);
        ah.setSize(790, 430);
        close();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Imports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Imports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Imports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Imports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Imports().setVisible(true);
            }
        });
    }
    void select(){
        try{
             Class.forName("oracle.jdbc.driver.OracleDriver");
             Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","tiger");
             PreparedStatement ps = conn.prepareStatement("SELECT *  FROM PLACE_ORDER WHERE MODEL=? ");
             ps.setString(1, (String) icombo.getSelectedItem());
             ResultSet rs = ps.executeQuery();
             while(rs.next())
             {
                 String sbrand = rs.getString("BRAND");
                 brand.setText(sbrand);
                 String smodel = rs.getString("MODEL");
                 model.setText(smodel);
                 
                 
            }
             
             
        }
        catch(Exception e){
        
            JOptionPane.showMessageDialog(null, "Worng ","Click ok to try angain",JOptionPane.ERROR_MESSAGE);
        } 
    }
    void filecombo()
    {
        try{
             Class.forName("oracle.jdbc.driver.OracleDriver");
             Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","tiger");
             PreparedStatement ps = conn.prepareStatement("SELECT * FROM PLACE_ORDER ");
             
             ResultSet rs = ps.executeQuery();
             while(rs.next())
             {
                 String carnum = rs.getString("MODEL");
                 icombo.addItem(carnum);
                 
             }
             
        }
        catch(Exception e){
        
            JOptionPane.showMessageDialog(null, "combo failde","Click ok to try angain",JOptionPane.ERROR_MESSAGE);
            
        }
    }
    void UpdateTable()
    {
        try{
             Class.forName("oracle.jdbc.driver.OracleDriver");
             Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","tiger");
             PreparedStatement ps = conn.prepareStatement("SELECT * FROM  PLACE_ORDER ");
             
             ResultSet rs = ps.executeQuery();
             porder.setModel(DbUtils.resultSetToTableModel(rs));
             
        }
        catch(Exception e){
        
            JOptionPane.showMessageDialog(null, "table creation failed","Click ok to try angain",JOptionPane.ERROR_MESSAGE);
        }
    }
    public void close()
    {
        WindowEvent winCloseEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winCloseEvent);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brand;
    private javax.swing.JTextField carnumber;
    private javax.swing.JTextField colour;
    private javax.swing.JTextField date;
    private javax.swing.JComboBox<String> icombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel model;
    private javax.swing.JTextField numofcars;
    private javax.swing.JTable porder;
    private javax.swing.JTextField price;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
