/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carshipment_project;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


public class PurchaseCar extends javax.swing.JFrame {

    String uname;
    public PurchaseCar(String name) {
        initComponents();
        
        filecombo();
        uname = name;
        UpdateTable();
        
    }
    public void close()
    {
        WindowEvent winCloseEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winCloseEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cartable = new javax.swing.JTable();
        carnumber = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        purchase = new javax.swing.JButton();
        ammount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Due = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        havetoPay = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        slcbrand = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        slcmodel = new javax.swing.JLabel();
        select = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        cartable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Brand", "Model", "Colour", "Status", "Price", "Car Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(cartable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 17, 730, 166);

        carnumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        carnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carnumberActionPerformed(evt);
            }
        });
        getContentPane().add(carnumber);
        carnumber.setBounds(155, 191, 85, 22);

        jLabel1.setText("Select Car Number");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 194, 108, 16);

        purchase.setText("Purchase");
        purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseActionPerformed(evt);
            }
        });
        getContentPane().add(purchase);
        purchase.setBounds(290, 285, 120, 25);

        ammount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ammountActionPerformed(evt);
            }
        });
        getContentPane().add(ammount);
        ammount.setBounds(155, 286, 102, 22);

        jLabel2.setText("Paid Ammount");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 289, 83, 16);

        jLabel3.setText("Due");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 356, 35, 16);

        Due.setText("----");
        getContentPane().add(Due);
        Due.setBounds(155, 352, 102, 24);

        jLabel4.setText(" Have to Pay");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(371, 233, 71, 16);

        havetoPay.setText("-------");
        getContentPane().add(havetoPay);
        havetoPay.setBounds(469, 233, 110, 16);

        jLabel5.setText("Brand");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(12, 233, 33, 16);

        slcbrand.setText("----------");
        getContentPane().add(slcbrand);
        slcbrand.setBounds(90, 233, 50, 16);

        jLabel7.setText("Model");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(180, 233, 34, 16);

        slcmodel.setText("---------");
        getContentPane().add(slcmodel);
        slcmodel.setBounds(264, 233, 45, 16);

        select.setText("Select");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        getContentPane().add(select);
        select.setBounds(285, 190, 100, 25);

        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 380, 161, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carshipment_project/Flag_of_Taliban_(original).svg.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 830, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carnumberActionPerformed
         
    }//GEN-LAST:event_carnumberActionPerformed

    private void ammountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ammountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ammountActionPerformed

    private void purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseActionPerformed

       try
       {int balance = 0;
       int totaldue =0;
       int htpay = Integer.parseInt(havetoPay.getText());
       int paid  = Integer.parseInt(ammount.getText());
       
       int due = htpay - paid;
       
       Due.setText(String.valueOf(due));
       setSell_info();
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, "Worng input","Click ok to try angain",JOptionPane.ERROR_MESSAGE);
       }
       
       
        
    }//GEN-LAST:event_purchaseActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        finalselect();
    }//GEN-LAST:event_selectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UserHome hm = new UserHome(uname);
        hm.setVisible(true);
        hm.setSize(730, 430);
        close();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    void finalselect(){
        try{
             Class.forName("oracle.jdbc.driver.OracleDriver");
             Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","tiger");
             PreparedStatement ps = conn.prepareStatement("SELECT *  FROM CAR WHERE CAR_NUMBER=? ");
             ps.setString(1, (String) carnumber.getSelectedItem());
             ResultSet rs = ps.executeQuery();
             while(rs.next())
             {
                 String pay = rs.getString("PRICE");
                 havetoPay.setText(pay);
                 String brnd = rs.getString("BRAND");
                 slcbrand.setText(brnd);
                 String mdl = rs.getString("CAR_MODEL");
                 slcmodel.setText(mdl);
                 
                 
             }
             
             
             
        }
        catch(Exception e){
        
            JOptionPane.showMessageDialog(null, "Worng password or user name","Click ok to try angain",JOptionPane.ERROR_MESSAGE);
        } 
    }
    void filecombo()
    {
        try{
             Class.forName("oracle.jdbc.driver.OracleDriver");
             Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","tiger");
             PreparedStatement ps = conn.prepareStatement("SELECT * FROM CAR ");
             
             ResultSet rs = ps.executeQuery();
             while(rs.next())
             {
                 String carnum = rs.getString("CAR_NUMBER");
                 carnumber.addItem(carnum);
                 
             }
             
        }
        catch(Exception e){
        
            JOptionPane.showMessageDialog(null, "combo failde","Click ok to try angain",JOptionPane.ERROR_MESSAGE);
            
        }
    }
    
    void UpdateTable()
    {
        try{
             Class.forName("oracle.jdbc.driver.OracleDriver");
             Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","tiger");
             PreparedStatement ps = conn.prepareStatement("SELECT BRAND,CAR_MODEL,COLOUR,STATUS,PRICE,CAR_NUMBER FROM CAR ");
             
             ResultSet rs = ps.executeQuery();
             cartable.setModel(DbUtils.resultSetToTableModel(rs));
             
        }
        catch(Exception e){
        
            JOptionPane.showMessageDialog(null, "table creation failed","Click ok to try angain",JOptionPane.ERROR_MESSAGE);
        }
    }
    void setSell_info()
    {
     try{
             Class.forName("oracle.jdbc.driver.OracleDriver");
             Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","tiger");
             PreparedStatement s = conn.prepareStatement("SELECT NUMBER_OF_CAR FROM CAR WHERE CAR_NUMBER=? ");
             s.setString(1, (String) carnumber.getSelectedItem());
             ResultSet rs = s.executeQuery();
             while(rs.next())
             {
             
                 String num = rs.getString("NUMBER_OF_CAR");
                 int n = Integer.parseInt(num) - 1;
                 PreparedStatement ps = conn.prepareStatement("UPDATE CAR SET NUMBER_OF_CAR = ? WHERE CAR_NUMBER=? ");
                 ps.setString(1,String.valueOf(n));
                 ps.setString(2, (String) carnumber.getSelectedItem());
                 ps.executeQuery();
             }
             
             setAvailable();
             
             
             PreparedStatement ps = conn.prepareStatement("INSERT INTO SELL_INFO VALUES(?,?,?,?,?,?)");
             ps.setString(1,uname);
             ps.setString(2,slcbrand.getText());
             ps.setString(3,slcmodel.getText());
             ps.setString(4,ammount.getText());
             ps.setString(5,Due.getText());
             ps.setString(6, (String) carnumber.getSelectedItem());
             ps.executeQuery();
              JOptionPane.showMessageDialog(null, "Purchesed","Click ok to try angain",JOptionPane.ERROR_MESSAGE);
             
             
             
             
             
             
        }
        catch(Exception e){
        
            JOptionPane.showMessageDialog(null, "Purchesed fail","Click ok to try angain",JOptionPane.ERROR_MESSAGE);
        } 
    }
    
    void setAvailable()
    {
        try{
             Class.forName("oracle.jdbc.driver.OracleDriver");
             Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","tiger");
             PreparedStatement ps = conn.prepareStatement("SELECT NUMBER_OF_CAR FROM CAR WHERE CAR_NUMBER=? ");
             ps.setString(1, (String) carnumber.getSelectedItem());
             ResultSet rs = ps.executeQuery();
             while(rs.next())
             {
                 String num = rs.getString("NUMBER_OF_CAR");
                 if(Integer.parseInt(num) < 1)
                 {
                 
                     PreparedStatement delcar = conn.prepareStatement("DELETE FROM CAR WHERE CAR_NUMBER =? ");
                     delcar.setString(1, (String) carnumber.getSelectedItem());
                     delcar.executeQuery();
                     PurchaseCar pcar = new PurchaseCar(uname);
                     pcar.setVisible(true);
                     pcar.setSize(790, 460);
                     close();
                 }
                 else{
                 }
                 
                 
                 }
             }
             
             
             
        
        catch(Exception e){
        
            JOptionPane.showMessageDialog(null, "Failed","Click ok to try angain",JOptionPane.ERROR_MESSAGE);
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Due;
    private javax.swing.JTextField ammount;
    private javax.swing.JComboBox<String> carnumber;
    private javax.swing.JTable cartable;
    private javax.swing.JLabel havetoPay;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton purchase;
    private javax.swing.JButton select;
    private javax.swing.JLabel slcbrand;
    private javax.swing.JLabel slcmodel;
    // End of variables declaration//GEN-END:variables
}
