/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carshipment_project;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class UserAccount extends javax.swing.JFrame {

    /**
     * Creates new form UserAccount
     */
    String name;
    public UserAccount(String uname){
    
        initComponents();
        set(uname);
        name= uname;
    }
    public void close()
    {
        WindowEvent winCloseEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winCloseEvent);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        billpaid = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        due = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        paydue = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("User Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 70, 67, 16);

        username.setText("----------------");
        getContentPane().add(username);
        username.setBounds(193, 70, 107, 16);

        jLabel2.setText("Bill Paid");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 122, 67, 16);

        billpaid.setText("---------------");
        getContentPane().add(billpaid);
        billpaid.setBounds(193, 122, 84, 16);

        jLabel3.setText("Due");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 173, 56, 16);

        due.setText("-------------");
        getContentPane().add(due);
        due.setBounds(193, 173, 84, 16);

        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(261, 288, 201, 25);

        jButton2.setText("Pay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(362, 220, 90, 25);

        jLabel4.setText("Pay Due");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 224, 46, 16);
        getContentPane().add(paydue);
        paydue.setBounds(193, 221, 131, 22);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carshipment_project/25-cars-worth-waiting-for-lp-ford-gt-photo-658253-s-original.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 950, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UserHome hm = new UserHome(name);
        hm.setVisible(true);
        hm.setSize(730, 430);
        close();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","tiger");
            PreparedStatement ps = conn.prepareStatement("UPDATE SELL_INFO SET PAID=?,DUE=? WHERE NAME=? ");
            int olddue  = Integer.parseInt(due.getText());
            int oldpaid  = Integer.parseInt(billpaid.getText());
            int pdue  = Integer.parseInt(paydue.getText());
            int remain = olddue - pdue;
            int npaid = oldpaid + pdue;
            billpaid.setText(String.valueOf(npaid));
            due.setText(String.valueOf(remain));
            ps.setString(1, String.valueOf(npaid));
            ps.setString(2, String.valueOf(remain));
            ps.setString(3, username.getText());
            ps.executeQuery();
            paydue.setText("");
            UserAccount uac =new UserAccount(username.getText());
            uac.setVisible(true);
            uac.setSize(790, 430);
            close();
            
            
            
            
            
            
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    void set(String uname)
    {
        username.setText(uname);
        try{
             Class.forName("oracle.jdbc.driver.OracleDriver");
             Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","tiger");
             PreparedStatement ps = conn.prepareStatement("SELECT * FROM SELL_INFO WHERE NAME=? ");
             ps.setString(1, uname);
             
             ResultSet rs = ps.executeQuery();
             while(rs.next())
             {
                 String paid = rs.getString("PAID");
                 billpaid.setText(paid);
                 String duebill = rs.getString("DUE");
                 due.setText(duebill);
             }
             
        }
        catch(Exception e){
        
            JOptionPane.showMessageDialog(null, "Worng password or user name","Click ok to try angain",JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel billpaid;
    private javax.swing.JLabel due;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField paydue;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
